### ISSUE TITLE
Support liquid 4

### ISSUE THREAD

**Issue by swsnr** [bdesham/pluralize#7]
As in https://github.com/bdesham/reading_time/issues/3, I'd like to use this plugin with Jekyll 3.5 and Liquid 4.  Could you update it to Liquid 4?

**Comment by csware** [comment]
It seems to be sufficient to remove `, '< 4.0'` on line `s.add_runtime_dependency('liquid', ['>= 2.6', '< 4.0'])` in  `liquid_pluralize.gemspec`.

**Comment by bdesham** [comment]
Fixed in version 1.0.3, available on RubyGems now.
